kind: pipeline
name: default

steps:
- name: test
  image: rust:1.30
  commands:
  - cd test_drone 
  - pwd
  - cargo build --verbose --all
  - cargo test --verbose --all
  - echo "HOME FOLDER = " $HOME
  - ls $HOME

---
kind: pipeline
type: exec
name: integration

platform:
  os: linux
  arch: amd64

steps:
- name: integration
  commands:
  - export $HOME/.cargo/bin:$PATH
  - export SGX_MODE=HW
  - export NETWORK_ID=ab
  - echo "HOME FOLDER = " $HOME
  - pwd
  - cd test_drone_integration
  - cargo build
  