[package]
name = "code"
version = "0.1.0"
authors = ["jongwhan lee <leejw51@gmail.com>"]
edition = "2018"

[dependencies]
hex = ""
serde_json= ""
serde = { version = "1.0", features = ["derive"] }
serde_derive= ""
bincode= ""
lazy_static=""
blake2=""
structopt=""
chrono=""