[package]
name = "test_page"
version = "0.1.0"
authors = ["jonghwan <jonghwan@crypto.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
